import { type BunPlugin } from "bun";

const prod = process.argv.includes("production");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN
if you want to view the source, please visit the github repository of this plugin
*/

// Polyfill for import.meta in CommonJS context
if (typeof import_meta === 'undefined') {
  var import_meta = {
    url: typeof __filename !== 'undefined' ? 'file://' + __filename : 'file:///obsidian-plugin'
  };
}
`;

/**
 * Plugin to provide a shim for node:module in browser/Electron renderer context.
 * Required by @langchain/community which imports createRequire from node:module.
 */
const nodeModuleShim: BunPlugin = {
  name: "node-module-shim",
  setup(build) {
    build.onResolve({ filter: /^node:module$/ }, (args) => ({
      path: args.path,
      namespace: "node-module-shim",
    }));

    build.onLoad({ filter: /.*/, namespace: "node-module-shim" }, () => ({
      contents: `
// Shim for node:module in Electron/Obsidian environment (CommonJS format)
module.exports = {
  createRequire: function(filename) {
    if (typeof require !== 'undefined') {
      return require;
    }
    return function shimmedRequire(id) {
      throw new Error('Dynamic require of "' + id + '" is not supported in this environment');
    };
  }
};
`,
      loader: "js",
    }));
  },
};

/**
 * Plugin to inline .wasm files as binary data and provide an instantiation wrapper.
 */
const wasmPlugin: BunPlugin = {
  name: "wasm",
  setup(build) {
    build.onResolve({ filter: /\.wasm$/ }, (args) => {
      if (args.namespace === "wasm-stub") {
        return { path: args.path, namespace: "wasm-binary" };
      }
      if (args.resolveDir === "") return;
      const resolved = Bun.pathIsAbsolute(args.path)
        ? args.path
        : `${args.resolveDir}/${args.path}`;
      return { path: resolved, namespace: "wasm-stub" };
    });

    build.onLoad({ filter: /.*/, namespace: "wasm-stub" }, (args) => ({
      contents: `import wasm from ${JSON.stringify(args.path)}
        export default (imports) =>
          WebAssembly.instantiate(wasm, imports).then(
            result => result.instance.exports)`,
    }));

    build.onLoad({ filter: /.*/, namespace: "wasm-binary" }, async (args) => ({
      contents: await Bun.file(args.path).arrayBuffer(),
      loader: "binary",
    }));
  },
};

const result = await Bun.build({
  entrypoints: ["src/main.ts"],
  outdir: ".",
  naming: "main.js",
  target: "browser",
  format: "cjs",
  sourcemap: prod ? "none" : "inline",
  minify: prod,
  define: {
    global: "window",
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    "import.meta.url": "import_meta.url",
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Node.js built-in modules (available in Electron) - except node:module which we shim
    "node:fs",
    "node:path",
    "node:url",
    "node:buffer",
    "node:stream",
    "node:crypto",
    "node:async_hooks",
  ],
  banner,
  plugins: [nodeModuleShim, wasmPlugin],
});

if (!result.success) {
  for (const message of result.logs) {
    console.error(message);
  }
  process.exit(1);
}

// Post-process: replace import.meta references that Bun preserves with target:node.
// Obsidian loads plugins as CJS where import.meta is illegal.
const outfile = result.outputs[0];
let code = await outfile.text();
code = code
  .replaceAll("import.meta.url", "import_meta.url")
  .replaceAll("import.meta.env", "undefined");
await Bun.write("main.js", code);

console.log(`Build complete (${prod ? "production" : "development"})`);
